//
//  RootInteractor.swift
//  Architecture
//
//  Created Dmitri Utmanov on 20/02/16.
//  Copyright © 2016 Dmitriy Utmanov. All rights reserved.
//
//  Generated by Swift-Viper templates. Find latest version at https://github.com/Nikita2k/SwiftViper
//

import Foundation

protocol RootInteractorInputProtocol: class {
    
    weak var presenter: RootInteractorOutputProtocol! { get set }
    
}

protocol RootInteractorOutputProtocol: class {
    
}

class RootInteractor {

    weak var presenter: RootInteractorOutputProtocol!
    
}

extension RootInteractor: RootInteractorInputProtocol {
    
}
