//
//  ServiceLocatorContainer.swift
//  Architecture
//
//  Created Dmitri Utmanov on 24/02/16.
//  Copyright © 2016 Dmitriy Utmanov. All rights reserved.
//
//  Generated by Swift-Viper templates. Find latest version at https://github.com/Nikita2k/SwiftViper
//

import Foundation
import Swinject

class ServiceLocatorContainer: AssemblyType {
    
    func assemble(container: Container) {
        container.register(RootAssembler.self) { r in
            let delegete = (UIApplication.sharedApplication().delegate as! AppDelegate)
            return RootAssembler(parentAssembler: delegete.serviceLocatorAssembler)
        }
    }
    
}